# Generated by Django 5.2.13 on 2026-05-13 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addresses', '0001_initial'),
        ('products', '0002_producttype_alter_product_category_productattribute_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('pending_payment', 'Chờ thanh toán'), ('paid', 'Đã thanh toán'), ('processing', 'Đang xử lý'), ('shipping', 'Đang giao hàng'), ('completed', 'Đã giao hàng'), ('cancelled', 'Đã hủy')], default='pending_payment', max_length=30)),
                ('payment_method', models.CharField(choices=[('vietqr', 'VIETQR'), ('bank', 'Chuyển khoản ngân hàng'), ('atm', 'Thẻ ATM nội địa / Napas'), ('visa', 'Visa / Mastercard'), ('cod', 'Thanh toán khi nhận hàng')], max_length=20)),
                ('payment_status', models.CharField(default='pending', max_length=30)),
                ('total_amount', models.DecimalField(decimal_places=0, default=0, max_digits=14)),
                ('receiver_name', models.CharField(max_length=150)),
                ('receiver_phone', models.CharField(max_length=20)),
                ('receiver_address', models.TextField()),
                ('bank_name', models.CharField(default='VIETCOMBANK - CN Hồ Chí Minh', max_length=120)),
                ('bank_account_number', models.CharField(default='007 100 125 1585', max_length=40)),
                ('bank_account_name', models.CharField(default='CÔNG TY TNHH FUJIFILM VIỆT NAM', max_length=180)),
                ('transfer_content', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='addresses.address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Đơn hàng',
                'verbose_name_plural': 'Đơn hàng',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.PositiveIntegerField()),
                ('product_name', models.CharField(max_length=200)),
                ('variant_name', models.CharField(max_length=100)),
                ('product_image', models.URLField(blank=True, default='')),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=14)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('subtotal', models.DecimalField(decimal_places=0, max_digits=14)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productvariant')),
            ],
            options={
                'verbose_name': 'Sản phẩm trong đơn',
                'verbose_name_plural': 'Sản phẩm trong đơn',
            },
        ),
    ]
