# Generated by Django 5.2.13 on 2026-04-28 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'Loại sản phẩm',
                'verbose_name_plural': 'Loại sản phẩm',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Danh mục chi tiết (tuỳ chọn)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category'),
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(blank=True, default='', help_text='Nhóm thông số, ví dụ: Cảm biến, CPU, Màn hình...', max_length=100)),
                ('name', models.CharField(help_text='Tên thông số', max_length=150)),
                ('value', models.CharField(help_text='Giá trị', max_length=500)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='products.product')),
            ],
            options={
                'verbose_name': 'Thông số kỹ thuật',
                'verbose_name_plural': 'Thông số kỹ thuật',
                'ordering': ['group', 'order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(help_text='Loại: Camera, Lens, Film, Instax, Phụ kiện...', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.producttype'),
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='products.producttype')),
            ],
            options={
                'verbose_name': 'Dòng sản phẩm',
                'verbose_name_plural': 'Dòng sản phẩm',
                'ordering': ['product_type', 'name'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='products.series'),
        ),
        migrations.AddField(
            model_name='product',
            name='series',
            field=models.ForeignKey(blank=True, help_text='Dòng: GFX Series, X Series, Instax...', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.series'),
        ),
        migrations.DeleteModel(
            name='ProductSpec',
        ),
    ]
